spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise_ai_db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
gemini:
  api-key: ${GEMINI_API_KEY}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent